name: slurm-wasimoff-system
# TODO: add logging

services:
  controller:
    build:
      context: .
      target: controller
    cpu_count: 2
    cpuset: 0-1
    container_name: controller
    hostname: controller
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    
  com0:
    build:
      context: .
      target: computer
    cpu_count: 1
    cpuset: "3"
    container_name: com0
    hostname: com0
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  com1:
    build:
      context: .
      target: computer
    cpu_count: 1
    cpuset: "4"
    container_name: com1
    hostname: com1
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  com2:
    build:
      context: .
      target: computer
    cpu_count: 1
    cpuset: "5"
    container_name: com2
    hostname: com2
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw