name: slurm-wasimoff-system
# TODO: change into static network definition (hostname, ip-address, extra-hosts for host mappings etc.)
# TODO: add logging

services:
  controller:
    image: niweil/controller:0.0.0
    cpu_count: 2
    cpuset: 0,1
    container_name: controller-node
    hostname: controller
    extra-hosts:
      - "computer-a=127.0.0.3"
      - "computer-b=127.0.0.4"
    networks: 
      mybridge:
        ipv4-address: 127.0.0.2
  compute-node-a:
    image: niweil/compute-node:0.0.0
    cpu_count: 1
    cpuset: 3 # adapt onto target system
    container_name: compute-node-a
    hostname: computer-a
    extra-hosts:
      - "controller=127.0.0.2"
      - "computer-b=127.0.0.4"
    networks: 
      mybridge:
        ipv4-address: 127.0.0.3

  compute-node-b:
    image: niweil/compute-node:0.0.0
    cpu_count: 1
    cpuset: 4 # adapt onto target system
    container_name: compute-node-b
    hostname: computer-b
    extra-hosts:
      - "controller=127.0.0.2"
      - "computer-a=127.0.0.3"
    networks: 
      mybridge:
        ipv4-address: 127.0.0.4

# TODO: add further configs if necessary
# TODO: Add ipam with subnet config
networks:
  mybridge:
    driver: bridge
    config:
      - subnet: 127.0.0.0/29