name: slurm-wasimoff-system
# TODO: change into static network definition (hostname, ip-address, extra-hosts for host mappings etc.)
# TODO: add logging

services:
  controller:
    build:
      context: .
      target: controller
    cpu_count: 2
    cpuset: 0-1
    container_name: controller
    hostname: controller
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    
  computer-a:
    build:
      context: .
      target: computer
    cpu_count: 1
    cpuset: "3"
    container_name: compute-node-a
    hostname: computer-a
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  computer-b:
    build:
      context: .
      target: computer
    cpu_count: 1
    cpuset: "4"
    container_name: compute-node-b
    hostname: computer-b
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw